query GetQuote($id: ID!) {
  findOneQuoteType(id: $id) {
    id
    text
    createdAt
    userId

    user {
      id
      createdAt
      updatedAt
      name
      username
    }

    commentsSummary {
      totalCount
    }

    commentsPaginated {
      items {
        id
        text
        userId
        quoteId
        createdAt
        updatedAt
        user {
          username
        }
      }
    }

    reactionsSummary {
      totalCount
      counts {
        type
        count
      }
    }
    reactionsPaginated(includeUsers: true) {
      items {
        id
        type
        userId
      }
    }
  }
}
